potentP2X4coop2.getTotalCurrent=@ getTotalCurrentpotentP2X4coop2;
potentP2X4coop2.ode=@ modelODEpotentP2X4coop2;
potentP2X4coop2.pulseODE=@ modelPulseODEpotentP2X4coop2;
potentP2X4coop2.perfusionResponse=@ perfusionResponsepotentP2X4coop2;
potentP2X4coop2.naivePerfusionResponse=@ naivePerfusionResponsepotentP2X4coop2;
potentP2X4coop2.naivePerfusionSSE=@ naivePerfusionSSEpotentP2X4coop2;
potentP2X4coop2.naivePerfusionErrVec=@ naivePerfusionErrVecpotentP2X4coop2;
potentP2X4coop2.naivePerfusionVarSSE=@ naivePerfusionVarSSEpotentP2X4coop2;
potentP2X4coop2.naivePerfusionResponseExp=@ naivePerfusionResponsepotentP2X4coop2;
potentP2X4coop2.naivePerfusionSSEExp=@ naivePerfusionSSEpotentP2X4coop2;
potentP2X4coop2.naivePerfusionSSEIntegrator=@ naivePerfusionSSEIntegratorpotentP2X4coop2;
potentP2X4coop2.setParams=@ setParamspotentP2X4coop2;
potentP2X4coop2.setAuxiliary=@ setAuxiliarypotentP2X4coop2;
potentP2X4coop2.overrideGlobals=@ overrideGlobalspotentP2X4coop2;
potentP2X4coop2.getOpen=@ getOpenpotentP2X4coop2;
potentP2X4coop2.getDilated=@ getDilatedpotentP2X4coop2;
potentP2X4coop2.getWatchedStates=@ getWatchedStatespotentP2X4coop2;
potentP2X4coop2.getWatchedLabels=@ getWatchedLabelspotentP2X4coop2;
potentP2X4coop2.naive=@ getNaivepotentP2X4coop2;

save('potentP2X4coop2.mat','potentP2X4coop2')