P2X4StackDeMix4.getTotalCurrent=@ getTotalCurrentP2X4StackDeMix4;
P2X4StackDeMix4.ode=@ modelODEP2X4StackDeMix4;
P2X4StackDeMix4.pulseODE=@ modelPulseODEP2X4StackDeMix4;
P2X4StackDeMix4.perfusionResponse=@ perfusionResponseP2X4StackDeMix4;
P2X4StackDeMix4.naivePerfusionResponse=@ naivePerfusionResponseP2X4StackDeMix4;
P2X4StackDeMix4.naivePerfusionResponseIV=@ naivePerfusionResponseIVP2X4StackDeMix4;
P2X4StackDeMix4.naivePerfusionSSE=@ naivePerfusionSSEP2X4StackDeMix4;
P2X4StackDeMix4.naivePerfusionErrVec=@ naivePerfusionErrVecP2X4StackDeMix4;
P2X4StackDeMix4.naivePerfusionVarSSE=@ naivePerfusionVarSSEP2X4StackDeMix4;
P2X4StackDeMix4.naivePerfusionResponseExp=@ naivePerfusionResponseP2X4StackDeMix4;
P2X4StackDeMix4.naivePerfusionSSEExp=@ naivePerfusionSSEP2X4StackDeMix4;
P2X4StackDeMix4.naivePerfusionSSEIntegrator=@ naivePerfusionSSEIntegratorP2X4StackDeMix4;
P2X4StackDeMix4.setParams=@ setParamsP2X4StackDeMix4;
P2X4StackDeMix4.setAuxiliary=@ setAuxiliaryP2X4StackDeMix4;
P2X4StackDeMix4.overrideGlobals=@ overrideGlobalsP2X4StackDeMix4;
P2X4StackDeMix4.getOpen=@ getOpenP2X4StackDeMix4;
P2X4StackDeMix4.getDilated=@ getDilatedP2X4StackDeMix4;
P2X4StackDeMix4.getWatchedStates=@ getWatchedStatesP2X4StackDeMix4;
P2X4StackDeMix4.getWatchedLabels=@ getWatchedLabelsP2X4StackDeMix4;
P2X4StackDeMix4.naive=@ getNaiveP2X4StackDeMix4;

save('P2X4StackDeMix4.mat','P2X4StackDeMix4')