potentP2X4poolindepfull.getTotalCurrent=@ getTotalCurrentpotentP2X4poolindepfull;
potentP2X4poolindepfull.ode=@ modelODEpotentP2X4poolindepfull;
potentP2X4poolindepfull.pulseODE=@ modelPulseODEpotentP2X4poolindepfull;
potentP2X4poolindepfull.perfusionResponse=@ perfusionResponsepotentP2X4poolindepfull;
potentP2X4poolindepfull.naivePerfusionResponse=@ naivePerfusionResponsepotentP2X4poolindepfull;
potentP2X4poolindepfull.naivePerfusionSSE=@ naivePerfusionSSEpotentP2X4poolindepfull;
potentP2X4poolindepfull.naivePerfusionVarSSE=@ naivePerfusionVarSSEpotentP2X4poolindepfull;
potentP2X4poolindepfull.naivePerfusionResponseExp=@ naivePerfusionResponsepotentP2X4poolindepfull;
potentP2X4poolindepfull.naivePerfusionSSEExp=@ naivePerfusionSSEpotentP2X4poolindepfull;
potentP2X4poolindepfull.naivePerfusionSSEIntegrator=@ naivePerfusionSSEIntegratorpotentP2X4poolindepfull;
potentP2X4poolindepfull.setParams=@ setParamspotentP2X4poolindepfull;
potentP2X4poolindepfull.setAuxiliary=@ setAuxiliarypotentP2X4poolindepfull;
potentP2X4poolindepfull.overrideGlobals=@ overrideGlobalspotentP2X4poolindepfull;
potentP2X4poolindepfull.getOpen=@ getOpenpotentP2X4poolindepfull;
potentP2X4poolindepfull.getDilated=@ getDilatedpotentP2X4poolindepfull;
potentP2X4poolindepfull.getWatchedStates=@ getWatchedStatespotentP2X4poolindepfull;
potentP2X4poolindepfull.getWatchedLabels=@ getWatchedLabelspotentP2X4poolindepfull;
potentP2X4poolindepfull.naive=@ getNaivepotentP2X4poolindepfull;

save('potentP2X4poolindepfull.mat','potentP2X4poolindepfull')