P2X4Stack2sub.getTotalCurrent=@ getTotalCurrentP2X4Stack2sub;
P2X4Stack2sub.ode=@ modelODEP2X4Stack2sub;
P2X4Stack2sub.pulseODE=@ modelPulseODEP2X4Stack2sub;
P2X4Stack2sub.perfusionResponse=@ perfusionResponseP2X4Stack2sub;
P2X4Stack2sub.naivePerfusionResponse=@ naivePerfusionResponseP2X4Stack2sub;
P2X4Stack2sub.naivePerfusionResponseIV=@ naivePerfusionResponseIVP2X4Stack2sub;
P2X4Stack2sub.naivePerfusionSSE=@ naivePerfusionSSEP2X4Stack2sub;
P2X4Stack2sub.naivePerfusionErrVec=@ naivePerfusionErrVecP2X4Stack2sub;
P2X4Stack2sub.naivePerfusionVarSSE=@ naivePerfusionVarSSEP2X4Stack2sub;
P2X4Stack2sub.naivePerfusionResponseExp=@ naivePerfusionResponseP2X4Stack2sub;
P2X4Stack2sub.naivePerfusionSSEExp=@ naivePerfusionSSEP2X4Stack2sub;
P2X4Stack2sub.naivePerfusionSSEIntegrator=@ naivePerfusionSSEIntegratorP2X4Stack2sub;
P2X4Stack2sub.setParams=@ setParamsP2X4Stack2sub;
P2X4Stack2sub.setAuxiliary=@ setAuxiliaryP2X4Stack2sub;
P2X4Stack2sub.overrideGlobals=@ overrideGlobalsP2X4Stack2sub;
P2X4Stack2sub.getOpen=@ getOpenP2X4Stack2sub;
P2X4Stack2sub.getDilated=@ getDilatedP2X4Stack2sub;
P2X4Stack2sub.getWatchedStates=@ getWatchedStatesP2X4Stack2sub;
P2X4Stack2sub.getWatchedLabels=@ getWatchedLabelsP2X4Stack2sub;
P2X4Stack2sub.naive=@ getNaiveP2X4Stack2sub;

save('P2X4Stack2sub.mat','P2X4Stack2sub')