potent1P2X4revcoop.getTotalCurrent=@ getTotalCurrentpotent1P2X4revcoop;
potent1P2X4revcoop.ode=@ modelODEpotent1P2X4revcoop;
potent1P2X4revcoop.pulseODE=@ modelPulseODEpotent1P2X4revcoop;
potent1P2X4revcoop.perfusionResponse=@ perfusionResponsepotent1P2X4revcoop;
potent1P2X4revcoop.naivePerfusionResponse=@ naivePerfusionResponsepotent1P2X4revcoop;
potent1P2X4revcoop.naivePerfusionSSE=@ naivePerfusionSSEpotent1P2X4revcoop;
potent1P2X4revcoop.naivePerfusionVarSSE=@ naivePerfusionVarSSEpotent1P2X4revcoop;
potent1P2X4revcoop.naivePerfusionResponseExp=@ naivePerfusionResponsepotent1P2X4revcoop;
potent1P2X4revcoop.naivePerfusionSSEExp=@ naivePerfusionSSEpotent1P2X4revcoop;
potent1P2X4revcoop.naivePerfusionSSEIntegrator=@ naivePerfusionSSEIntegratorpotent1P2X4revcoop;
potent1P2X4revcoop.setParams=@ setParamspotent1P2X4revcoop;
potent1P2X4revcoop.setAuxiliary=@ setAuxiliarypotent1P2X4revcoop;
potent1P2X4revcoop.getOpen=@ getOpenpotent1P2X4revcoop;
potent1P2X4revcoop.getDilated=@ getDilatedpotent1P2X4revcoop;
potent1P2X4revcoop.getWatchedStates=@ getWatchedStatespotent1P2X4revcoop;
potent1P2X4revcoop.getWatchedLabels=@ getWatchedLabelspotent1P2X4revcoop;

save('potent1P2X4revcoop.mat','potent1P2X4revcoop')