potent1P2X4coop.getTotalCurrent=@ getTotalCurrentpotent1P2X4coop;
potent1P2X4coop.ode=@ modelODEpotent1P2X4coop;
potent1P2X4coop.pulseODE=@ modelPulseODEpotent1P2X4coop;
potent1P2X4coop.perfusionResponse=@ perfusionResponsepotent1P2X4coop;
potent1P2X4coop.naivePerfusionResponse=@ naivePerfusionResponsepotent1P2X4coop;
potent1P2X4coop.naivePerfusionSSE=@ naivePerfusionSSEpotent1P2X4coop;
potent1P2X4coop.naivePerfusionVarSSE=@ naivePerfusionVarSSEpotent1P2X4coop;
potent1P2X4coop.naivePerfusionResponseExp=@ naivePerfusionResponsepotent1P2X4coop;
potent1P2X4coop.naivePerfusionSSEExp=@ naivePerfusionSSEpotent1P2X4coop;
potent1P2X4coop.naivePerfusionSSEIntegrator=@ naivePerfusionSSEIntegratorpotent1P2X4coop;
potent1P2X4coop.setParams=@ setParamspotent1P2X4coop;
potent1P2X4coop.setAuxiliary=@ setAuxiliarypotent1P2X4coop;
potent1P2X4coop.getOpen=@ getOpenpotent1P2X4coop;
potent1P2X4coop.getDilated=@ getDilatedpotent1P2X4coop;
potent1P2X4coop.getWatchedStates=@ getWatchedStatespotent1P2X4coop;
potent1P2X4coop.getWatchedLabels=@ getWatchedLabelspotent1P2X4coop;
potent1P2X4coop.naive=@ getNaivepotent1P2X4coop;

save('potent1P2X4coop.mat','potent1P2X4coop')