potentP2X4poolblock.getTotalCurrent=@ getTotalCurrentpotentP2X4poolblock;
potentP2X4poolblock.ode=@ modelODEpotentP2X4poolblock;
potentP2X4poolblock.pulseODE=@ modelPulseODEpotentP2X4poolblock;
potentP2X4poolblock.perfusionResponse=@ perfusionResponsepotentP2X4poolblock;
potentP2X4poolblock.naivePerfusionResponse=@ naivePerfusionResponsepotentP2X4poolblock;
potentP2X4poolblock.naivePerfusionSSE=@ naivePerfusionSSEpotentP2X4poolblock;
potentP2X4poolblock.naivePerfusionVarSSE=@ naivePerfusionVarSSEpotentP2X4poolblock;
potentP2X4poolblock.naivePerfusionResponseExp=@ naivePerfusionResponsepotentP2X4poolblock;
potentP2X4poolblock.naivePerfusionSSEExp=@ naivePerfusionSSEpotentP2X4poolblock;
potentP2X4poolblock.naivePerfusionSSEIntegrator=@ naivePerfusionSSEIntegratorpotentP2X4poolblock;
potentP2X4poolblock.setParams=@ setParamspotentP2X4poolblock;
potentP2X4poolblock.setAuxiliary=@ setAuxiliarypotentP2X4poolblock;
potentP2X4poolblock.overrideGlobals=@ overrideGlobalspotentP2X4poolblock;
potentP2X4poolblock.getOpen=@ getOpenpotentP2X4poolblock;
potentP2X4poolblock.getDilated=@ getDilatedpotentP2X4poolblock;
potentP2X4poolblock.getWatchedStates=@ getWatchedStatespotentP2X4poolblock;
potentP2X4poolblock.getWatchedLabels=@ getWatchedLabelspotentP2X4poolblock;
potentP2X4poolblock.naive=@ getNaivepotentP2X4poolblock;

save('potentP2X4poolblock.mat','potentP2X4poolblock')