P2X4StackDeMix3.getTotalCurrent=@ getTotalCurrentP2X4StackDeMix3;
P2X4StackDeMix3.ode=@ modelODEP2X4StackDeMix3;
P2X4StackDeMix3.pulseODE=@ modelPulseODEP2X4StackDeMix3;
P2X4StackDeMix3.perfusionResponse=@ perfusionResponseP2X4StackDeMix3;
P2X4StackDeMix3.naivePerfusionResponse=@ naivePerfusionResponseP2X4StackDeMix3;
P2X4StackDeMix3.naivePerfusionResponseIV=@ naivePerfusionResponseIVP2X4StackDeMix3;
P2X4StackDeMix3.naivePerfusionSSE=@ naivePerfusionSSEP2X4StackDeMix3;
P2X4StackDeMix3.naivePerfusionErrVec=@ naivePerfusionErrVecP2X4StackDeMix3;
P2X4StackDeMix3.naivePerfusionVarSSE=@ naivePerfusionVarSSEP2X4StackDeMix3;
P2X4StackDeMix3.naivePerfusionResponseExp=@ naivePerfusionResponseP2X4StackDeMix3;
P2X4StackDeMix3.naivePerfusionSSEExp=@ naivePerfusionSSEP2X4StackDeMix3;
P2X4StackDeMix3.naivePerfusionSSEIntegrator=@ naivePerfusionSSEIntegratorP2X4StackDeMix3;
P2X4StackDeMix3.setParams=@ setParamsP2X4StackDeMix3;
P2X4StackDeMix3.setAuxiliary=@ setAuxiliaryP2X4StackDeMix3;
P2X4StackDeMix3.overrideGlobals=@ overrideGlobalsP2X4StackDeMix3;
P2X4StackDeMix3.getOpen=@ getOpenP2X4StackDeMix3;
P2X4StackDeMix3.getDilated=@ getDilatedP2X4StackDeMix3;
P2X4StackDeMix3.getWatchedStates=@ getWatchedStatesP2X4StackDeMix3;
P2X4StackDeMix3.getWatchedLabels=@ getWatchedLabelsP2X4StackDeMix3;
P2X4StackDeMix3.naive=@ getNaiveP2X4StackDeMix3;

save('P2X4StackDeMix3.mat','P2X4StackDeMix3')