P2X4StackDeMix6.getTotalCurrent=@ getTotalCurrentP2X4StackDeMix6;
P2X4StackDeMix6.ode=@ modelODEP2X4StackDeMix6;
P2X4StackDeMix6.pulseODE=@ modelPulseODEP2X4StackDeMix6;
P2X4StackDeMix6.perfusionResponse=@ perfusionResponseP2X4StackDeMix6;
P2X4StackDeMix6.naivePerfusionResponse=@ naivePerfusionResponseP2X4StackDeMix6;
P2X4StackDeMix6.naivePerfusionResponseIV=@ naivePerfusionResponseIVP2X4StackDeMix6;
P2X4StackDeMix6.naivePerfusionSSE=@ naivePerfusionSSEP2X4StackDeMix6;
P2X4StackDeMix6.naivePerfusionErrVec=@ naivePerfusionErrVecP2X4StackDeMix6;
P2X4StackDeMix6.naivePerfusionVarSSE=@ naivePerfusionVarSSEP2X4StackDeMix6;
P2X4StackDeMix6.naivePerfusionResponseExp=@ naivePerfusionResponseP2X4StackDeMix6;
P2X4StackDeMix6.naivePerfusionSSEExp=@ naivePerfusionSSEP2X4StackDeMix6;
P2X4StackDeMix6.naivePerfusionSSEIntegrator=@ naivePerfusionSSEIntegratorP2X4StackDeMix6;
P2X4StackDeMix6.setParams=@ setParamsP2X4StackDeMix6;
P2X4StackDeMix6.setAuxiliary=@ setAuxiliaryP2X4StackDeMix6;
P2X4StackDeMix6.overrideGlobals=@ overrideGlobalsP2X4StackDeMix6;
P2X4StackDeMix6.getOpen=@ getOpenP2X4StackDeMix6;
P2X4StackDeMix6.getDilated=@ getDilatedP2X4StackDeMix6;
P2X4StackDeMix6.getWatchedStates=@ getWatchedStatesP2X4StackDeMix6;
P2X4StackDeMix6.getWatchedLabels=@ getWatchedLabelsP2X4StackDeMix6;
P2X4StackDeMix6.naive=@ getNaiveP2X4StackDeMix6;

save('P2X4StackDeMix6.mat','P2X4StackDeMix6')