potentP2X4revcoop2.getTotalCurrent=@ getTotalCurrentpotentP2X4revcoop2;
potentP2X4revcoop2.ode=@ modelODEpotentP2X4revcoop2;
potentP2X4revcoop2.pulseODE=@ modelPulseODEpotentP2X4revcoop2;
potentP2X4revcoop2.perfusionResponse=@ perfusionResponsepotentP2X4revcoop2;
potentP2X4revcoop2.naivePerfusionResponse=@ naivePerfusionResponsepotentP2X4revcoop2;
potentP2X4revcoop2.naivePerfusionSSE=@ naivePerfusionSSEpotentP2X4revcoop2;
potentP2X4revcoop2.naivePerfusionVarSSE=@ naivePerfusionVarSSEpotentP2X4revcoop2;
potentP2X4revcoop2.naivePerfusionResponseExp=@ naivePerfusionResponsepotentP2X4revcoop2;
potentP2X4revcoop2.naivePerfusionSSEExp=@ naivePerfusionSSEpotentP2X4revcoop2;
potentP2X4revcoop2.naivePerfusionSSEIntegrator=@ naivePerfusionSSEIntegratorpotentP2X4revcoop2;
potentP2X4revcoop2.setParams=@ setParamspotentP2X4revcoop2;
potentP2X4revcoop2.setAuxiliary=@ setAuxiliarypotentP2X4revcoop2;
potentP2X4revcoop2.getOpen=@ getOpenpotentP2X4revcoop2;
potentP2X4revcoop2.getDilated=@ getDilatedpotentP2X4revcoop2;
potentP2X4revcoop2.getWatchedStates=@ getWatchedStatespotentP2X4revcoop2;
potentP2X4revcoop2.getWatchedLabels=@ getWatchedLabelspotentP2X4revcoop2;
potentP2X4revcoop2.naive=@ getNaivepotentP2X4revcoop2;

save('potentP2X4revcoop2.mat','potentP2X4revcoop2')