potentP2X4coop3.getTotalCurrent=@ getTotalCurrentpotentP2X4coop3;
potentP2X4coop3.ode=@ modelODEpotentP2X4coop3;
potentP2X4coop3.pulseODE=@ modelPulseODEpotentP2X4coop3;
potentP2X4coop3.perfusionResponse=@ perfusionResponsepotentP2X4coop3;
potentP2X4coop3.naivePerfusionResponse=@ naivePerfusionResponsepotentP2X4coop3;
potentP2X4coop3.naivePerfusionSSE=@ naivePerfusionSSEpotentP2X4coop3;
potentP2X4coop3.naivePerfusionVarSSE=@ naivePerfusionVarSSEpotentP2X4coop3;
potentP2X4coop3.naivePerfusionResponseExp=@ naivePerfusionResponsepotentP2X4coop3;
potentP2X4coop3.naivePerfusionSSEExp=@ naivePerfusionSSEpotentP2X4coop3;
potentP2X4coop3.naivePerfusionSSEIntegrator=@ naivePerfusionSSEIntegratorpotentP2X4coop3;
potentP2X4coop3.setParams=@ setParamspotentP2X4coop3;
potentP2X4coop3.setAuxiliary=@ setAuxiliarypotentP2X4coop3;
potentP2X4coop3.getOpen=@ getOpenpotentP2X4coop3;
potentP2X4coop3.getDilated=@ getDilatedpotentP2X4coop3;
potentP2X4coop3.getWatchedStates=@ getWatchedStatespotentP2X4coop3;
potentP2X4coop3.getWatchedLabels=@ getWatchedLabelspotentP2X4coop3;

save('potentP2X4coop3.mat','potentP2X4coop3')