P2X4StackDeMix5.getTotalCurrent=@ getTotalCurrentP2X4StackDeMix5;
P2X4StackDeMix5.ode=@ modelODEP2X4StackDeMix5;
P2X4StackDeMix5.pulseODE=@ modelPulseODEP2X4StackDeMix5;
P2X4StackDeMix5.perfusionResponse=@ perfusionResponseP2X4StackDeMix5;
P2X4StackDeMix5.naivePerfusionResponse=@ naivePerfusionResponseP2X4StackDeMix5;
P2X4StackDeMix5.naivePerfusionResponseIV=@ naivePerfusionResponseIVP2X4StackDeMix5;
P2X4StackDeMix5.naivePerfusionSSE=@ naivePerfusionSSEP2X4StackDeMix5;
P2X4StackDeMix5.naivePerfusionErrVec=@ naivePerfusionErrVecP2X4StackDeMix5;
P2X4StackDeMix5.naivePerfusionVarSSE=@ naivePerfusionVarSSEP2X4StackDeMix5;
P2X4StackDeMix5.naivePerfusionResponseExp=@ naivePerfusionResponseP2X4StackDeMix5;
P2X4StackDeMix5.naivePerfusionSSEExp=@ naivePerfusionSSEP2X4StackDeMix5;
P2X4StackDeMix5.naivePerfusionSSEIntegrator=@ naivePerfusionSSEIntegratorP2X4StackDeMix5;
P2X4StackDeMix5.setParams=@ setParamsP2X4StackDeMix5;
P2X4StackDeMix5.setAuxiliary=@ setAuxiliaryP2X4StackDeMix5;
P2X4StackDeMix5.overrideGlobals=@ overrideGlobalsP2X4StackDeMix5;
P2X4StackDeMix5.getOpen=@ getOpenP2X4StackDeMix5;
P2X4StackDeMix5.getDilated=@ getDilatedP2X4StackDeMix5;
P2X4StackDeMix5.getWatchedStates=@ getWatchedStatesP2X4StackDeMix5;
P2X4StackDeMix5.getWatchedLabels=@ getWatchedLabelsP2X4StackDeMix5;
P2X4StackDeMix5.naive=@ getNaiveP2X4StackDeMix5;

save('P2X4StackDeMix5.mat','P2X4StackDeMix5')