P2X4StackDeMix2.getTotalCurrent=@ getTotalCurrentP2X4StackDeMix2;
P2X4StackDeMix2.ode=@ modelODEP2X4StackDeMix2;
P2X4StackDeMix2.pulseODE=@ modelPulseODEP2X4StackDeMix2;
P2X4StackDeMix2.perfusionResponse=@ perfusionResponseP2X4StackDeMix2;
P2X4StackDeMix2.naivePerfusionResponse=@ naivePerfusionResponseP2X4StackDeMix2;
P2X4StackDeMix2.naivePerfusionResponseIV=@ naivePerfusionResponseIVP2X4StackDeMix2;
P2X4StackDeMix2.naivePerfusionSSE=@ naivePerfusionSSEP2X4StackDeMix2;
P2X4StackDeMix2.naivePerfusionErrVec=@ naivePerfusionErrVecP2X4StackDeMix2;
P2X4StackDeMix2.naivePerfusionVarSSE=@ naivePerfusionVarSSEP2X4StackDeMix2;
P2X4StackDeMix2.naivePerfusionResponseExp=@ naivePerfusionResponseP2X4StackDeMix2;
P2X4StackDeMix2.naivePerfusionSSEExp=@ naivePerfusionSSEP2X4StackDeMix2;
P2X4StackDeMix2.naivePerfusionSSEIntegrator=@ naivePerfusionSSEIntegratorP2X4StackDeMix2;
P2X4StackDeMix2.setParams=@ setParamsP2X4StackDeMix2;
P2X4StackDeMix2.setAuxiliary=@ setAuxiliaryP2X4StackDeMix2;
P2X4StackDeMix2.overrideGlobals=@ overrideGlobalsP2X4StackDeMix2;
P2X4StackDeMix2.getOpen=@ getOpenP2X4StackDeMix2;
P2X4StackDeMix2.getDilated=@ getDilatedP2X4StackDeMix2;
P2X4StackDeMix2.getWatchedStates=@ getWatchedStatesP2X4StackDeMix2;
P2X4StackDeMix2.getWatchedLabels=@ getWatchedLabelsP2X4StackDeMix2;
P2X4StackDeMix2.naive=@ getNaiveP2X4StackDeMix2;

save('P2X4StackDeMix2.mat','P2X4StackDeMix2')