potentP2X4block.getTotalCurrent=@ getTotalCurrentpotentP2X4block;
potentP2X4block.ode=@ modelODEpotentP2X4block;
potentP2X4block.pulseODE=@ modelPulseODEpotentP2X4block;
potentP2X4block.perfusionResponse=@ perfusionResponsepotentP2X4block;
potentP2X4block.naivePerfusionResponse=@ naivePerfusionResponsepotentP2X4block;
potentP2X4block.naivePerfusionSSE=@ naivePerfusionSSEpotentP2X4block;
potentP2X4block.naivePerfusionVarSSE=@ naivePerfusionVarSSEpotentP2X4block;
potentP2X4block.naivePerfusionResponseExp=@ naivePerfusionResponsepotentP2X4block;
potentP2X4block.naivePerfusionSSEExp=@ naivePerfusionSSEpotentP2X4block;
potentP2X4block.naivePerfusionSSEIntegrator=@ naivePerfusionSSEIntegratorpotentP2X4block;
potentP2X4block.setParams=@ setParamspotentP2X4block;
potentP2X4block.setAuxiliary=@ setAuxiliarypotentP2X4block;
potentP2X4block.overrideGlobals=@ overrideGlobalspotentP2X4block;
potentP2X4block.getOpen=@ getOpenpotentP2X4block;
potentP2X4block.getDilated=@ getDilatedpotentP2X4block;
potentP2X4block.getWatchedStates=@ getWatchedStatespotentP2X4block;
potentP2X4block.getWatchedLabels=@ getWatchedLabelspotentP2X4block;
potentP2X4block.naive=@ getNaivepotentP2X4block;

save('potentP2X4block.mat','potentP2X4block')