potentP2X4cooprev.getTotalCurrent=@ getTotalCurrentpotentP2X4cooprev;
potentP2X4cooprev.ode=@ modelODEpotentP2X4cooprev;
potentP2X4cooprev.pulseODE=@ modelPulseODEpotentP2X4cooprev;
potentP2X4cooprev.perfusionResponse=@ perfusionResponsepotentP2X4cooprev;
potentP2X4cooprev.naivePerfusionResponse=@ naivePerfusionResponsepotentP2X4cooprev;
potentP2X4cooprev.naivePerfusionSSE=@ naivePerfusionSSEpotentP2X4cooprev;
potentP2X4cooprev.naivePerfusionVarSSE=@ naivePerfusionVarSSEpotentP2X4cooprev;
potentP2X4cooprev.naivePerfusionResponseExp=@ naivePerfusionResponsepotentP2X4cooprev;
potentP2X4cooprev.naivePerfusionSSEExp=@ naivePerfusionSSEpotentP2X4cooprev;
potentP2X4cooprev.naivePerfusionSSEIntegrator=@ naivePerfusionSSEIntegratorpotentP2X4cooprev;
potentP2X4cooprev.setParams=@ setParamspotentP2X4cooprev;
potentP2X4cooprev.setAuxiliary=@ setAuxiliarypotentP2X4cooprev;
potentP2X4cooprev.getOpen=@ getOpenpotentP2X4cooprev;
potentP2X4cooprev.getDilated=@ getDilatedpotentP2X4cooprev;
potentP2X4cooprev.getWatchedStates=@ getWatchedStatespotentP2X4cooprev;
potentP2X4cooprev.getWatchedLabels=@ getWatchedLabelspotentP2X4cooprev;

save('potentP2X4cooprev.mat','potentP2X4cooprev')