P2X4StackDeMix7.getTotalCurrent=@ getTotalCurrentP2X4StackDeMix7;
P2X4StackDeMix7.ode=@ modelODEP2X4StackDeMix7;
P2X4StackDeMix7.pulseODE=@ modelPulseODEP2X4StackDeMix7;
P2X4StackDeMix7.perfusionResponse=@ perfusionResponseP2X4StackDeMix7;
P2X4StackDeMix7.naivePerfusionResponse=@ naivePerfusionResponseP2X4StackDeMix7;
P2X4StackDeMix7.naivePerfusionResponseIV=@ naivePerfusionResponseIVP2X4StackDeMix7;
P2X4StackDeMix7.naivePerfusionSSE=@ naivePerfusionSSEP2X4StackDeMix7;
P2X4StackDeMix7.naivePerfusionErrVec=@ naivePerfusionErrVecP2X4StackDeMix7;
P2X4StackDeMix7.naivePerfusionVarSSE=@ naivePerfusionVarSSEP2X4StackDeMix7;
P2X4StackDeMix7.naivePerfusionResponseExp=@ naivePerfusionResponseP2X4StackDeMix7;
P2X4StackDeMix7.naivePerfusionSSEExp=@ naivePerfusionSSEP2X4StackDeMix7;
P2X4StackDeMix7.naivePerfusionSSEIntegrator=@ naivePerfusionSSEIntegratorP2X4StackDeMix7;
P2X4StackDeMix7.setParams=@ setParamsP2X4StackDeMix7;
P2X4StackDeMix7.setAuxiliary=@ setAuxiliaryP2X4StackDeMix7;
P2X4StackDeMix7.overrideGlobals=@ overrideGlobalsP2X4StackDeMix7;
P2X4StackDeMix7.getOpen=@ getOpenP2X4StackDeMix7;
P2X4StackDeMix7.getDilated=@ getDilatedP2X4StackDeMix7;
P2X4StackDeMix7.getWatchedStates=@ getWatchedStatesP2X4StackDeMix7;
P2X4StackDeMix7.getInfGeneratorMatrix=@ generatorMatrixP2X4StackDeMix7;
P2X4StackDeMix7.getWatchedLabels=@ getWatchedLabelsP2X4StackDeMix7;
P2X4StackDeMix7.naive=@ getNaiveP2X4StackDeMix7;

save('P2X4StackDeMix7.mat','P2X4StackDeMix7')