P2X4Stack3sub.getTotalCurrent=@ getTotalCurrentP2X4Stack3sub;
P2X4Stack3sub.ode=@ modelODEP2X4Stack3sub;
P2X4Stack3sub.pulseODE=@ modelPulseODEP2X4Stack3sub;
P2X4Stack3sub.perfusionResponse=@ perfusionResponseP2X4Stack3sub;
P2X4Stack3sub.naivePerfusionResponse=@ naivePerfusionResponseP2X4Stack3sub;
P2X4Stack3sub.naivePerfusionResponseIV=@ naivePerfusionResponseIVP2X4Stack3sub;
P2X4Stack3sub.naivePerfusionSSE=@ naivePerfusionSSEP2X4Stack3sub;
P2X4Stack3sub.naivePerfusionErrVec=@ naivePerfusionErrVecP2X4Stack3sub;
P2X4Stack3sub.naivePerfusionVarSSE=@ naivePerfusionVarSSEP2X4Stack3sub;
P2X4Stack3sub.naivePerfusionResponseExp=@ naivePerfusionResponseP2X4Stack3sub;
P2X4Stack3sub.naivePerfusionSSEExp=@ naivePerfusionSSEP2X4Stack3sub;
P2X4Stack3sub.naivePerfusionSSEIntegrator=@ naivePerfusionSSEIntegratorP2X4Stack3sub;
P2X4Stack3sub.setParams=@ setParamsP2X4Stack3sub;
P2X4Stack3sub.setAuxiliary=@ setAuxiliaryP2X4Stack3sub;
P2X4Stack3sub.overrideGlobals=@ overrideGlobalsP2X4Stack3sub;
P2X4Stack3sub.getOpen=@ getOpenP2X4Stack3sub;
P2X4Stack3sub.getDilated=@ getDilatedP2X4Stack3sub;
P2X4Stack3sub.getWatchedStates=@ getWatchedStatesP2X4Stack3sub;
P2X4Stack3sub.getWatchedLabels=@ getWatchedLabelsP2X4Stack3sub;
P2X4Stack3sub.naive=@ getNaiveP2X4Stack3sub;

save('P2X4Stack3sub.mat','P2X4Stack3sub')