ThreeP2X7Forward.getTotalCurrent=@ getTotalCurrentThreeP2X7Forward;
ThreeP2X7Forward.ode=@ modelODEThreeP2X7Forward;
ThreeP2X7Forward.naivePerfusionResponse=@ naivePerfusionResponseThreeP2X7Forward;
ThreeP2X7Forward.naivePerfusionSSE=@ naivePerfusionSSEThreeP2X7Forward;
ThreeP2X7Forward.naivePerfusionSSEIntegrator=@ naivePerfusionSSEIntegratorThreeP2X7Forward;
ThreeP2X7Forward.setParams=@ setParamsThreeP2X7Forward;
ThreeP2X7Forward.checkParams=@ checkParamsThreeP2X7Forward;
ThreeP2X7Forward.getOpen=@ getOpenThreeP2X7Forward;
ThreeP2X7Forward.getDilated=@ getDilatedThreeP2X7Forward;

save('ThreeP2X7Forward.mat','ThreeP2X7Forward')