ThreeP2X7ASymBack.getTotalCurrent=@ getTotalCurrentThreeP2X7ASymBack;
ThreeP2X7ASymBack.ode=@ modelODEThreeP2X7ASymBack;
ThreeP2X7ASymBack.naivePerfusionResponse=@ naivePerfusionResponseThreeP2X7ASymBack;
ThreeP2X7ASymBack.naivePerfusionSSE=@ naivePerfusionSSEThreeP2X7ASymBack;
ThreeP2X7ASymBack.naivePerfusionSSEIntegrator=@ naivePerfusionSSEIntegratorThreeP2X7ASymBack;
ThreeP2X7ASymBack.setParams=@ setParamsThreeP2X7ASymBack;
ThreeP2X7ASymBack.checkParams=@ checkParamsThreeP2X7ASymBack;
ThreeP2X7ASymBack.getOpen=@ getOpenThreeP2X7ASymBack;
ThreeP2X7ASymBack.getDilated=@ getDilatedThreeP2X7ASymBack;

save('ThreeP2X7ASymBack.mat','ThreeP2X7ASymBack')